[[redirects]]
  from = "/api"
  to = "https://concise-server.herokuapp.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"